# Generated by Django 5.1.4 on 2024-12-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the category of the book (e.g., Fiction, Non-Fiction, Science, etc.)', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='A URL-friendly version of the category name', max_length=100, unique=True, verbose_name='Category Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the publisher', max_length=255, verbose_name='Publisher Name')),
                ('website', models.URLField(blank=True, help_text='Enter the website of the publisher', max_length=255, verbose_name='Publisher Website')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the book', max_length=255, verbose_name='Book Title')),
                ('author', models.CharField(help_text='Enter the name of the author', max_length=255, verbose_name='Author')),
                ('publication_date', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Publication Date')),
                ('desc', models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=500, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the book', max_digits=10, verbose_name='Price')),
                ('category', models.ForeignKey(blank=True, help_text='Select the category of the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Category')),
                ('publisher', models.ForeignKey(blank=True, help_text='Select the publisher of the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.publisher', verbose_name='Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Enter the name of the reviewer', max_length=255, verbose_name='Reviewer Name')),
                ('review_text', models.TextField(help_text='Enter your review of the book', verbose_name='Review Text')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Enter a rating between 1 and 5', verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the review was created', verbose_name='Created At')),
                ('book', models.ForeignKey(help_text='Select the book for this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.book', verbose_name='Book')),
            ],
        ),
    ]
